fix: reconcile ci

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -30,5 +30,13 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+make integration-test
+
+if [ $? -ne 0 ];then 
+  echo "integration tests fails"
+  echo "either fix them or commit using 'git commit --no-verify' if failing is intended"
+  exit 1
+fi
+
 echo "all tests passed"
 exit 0
